export const HANDLE_ITEM_ADD = 'HANDLE_ITEM_ADD'
export const HANDLE_ITEM_REMOVE = 'HANDLE_ITEM_REMOVE'
export const HANDLE_ITEM_ERROR = 'HANDLE_ITEM_ERROR'

export const HANDLE_ITEM_KEY_BIND_EDIT = 'HANDLE_ITEM_KEY_BIND_EDIT'
export const HANDLE_ITEM_KEY_BIND_SAVE = 'HANDLE_ITEM_KEY_BIND_SAVE'
export const HANDLE_ITEM_KEY_BIND_REMOVE = 'HANDLE_ITEM_KEY_BIND_REMOVE'
export const HANDLE_ITEM_KEY_ONCHANGE = 'HANDLE_ITEM_KEY_ONCHANGE'

export const FILE_UPLOAD_INIT = 'FILE_UPLOAD_INIT'
export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR'
export const FILE_UPLOAD_PROGRESS = 'FILE_UPLOAD_PROGRESS'
export const FILE_UPLOAD_COMPLETE = 'FILE_UPLOAD_COMPLETE'
export const FILE_UPLOAD_RESET = 'FILE_UPLOAD_RESET'

export const KEY_PRESS = 'KEY_PRESS'
export const IS_PLAYING = 'IS_PLAYING'
export const HANDLE_ERROR = 'HANDLE_ERROR'

export const UPDATE_KEY_BINDINGS = 'UPDATE_KEY_BINDINGS'
export const IS_EDITING = 'IS_EDITING'
